library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -isrc
  - -Widentities
tests:
  notion-ocr-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notion-ocr
copyright: 2019 Yannick Gladow
maintainer: yannick.gladow@gmail.com
dependencies:
- temporary
- witherable
- uri-encode
- unordered-containers
- containers
- safe
- lens-aeson
- random
- aeson
- aeson-pretty
- exceptions
- lens
- wreq
- bytestring
- time
- http-client
- conduit
- http-conduit
- directory
- optparse-applicative
- process
- hspec
- mtl
- text
- url
- uuid
- filepath
- base >= 4.7 && < 5
name: notion-ocr
version: 0.1.3
extra-source-files:
- README.md
- ChangeLog.md
author: Yannick Gladow
github: githubuser/yannick-cw
license: BSD3
executables:
  notion-ocr-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notion-ocr
description: Please see the README on GitHub at <https://github.com/yannick-cw/notion-ocr#readme>
