name:                notion-ocr
version:             0.1.0.0
github:              "githubuser/yannick-cw"
license:             BSD3
author:              "Yannick Gladow"
maintainer:          "yannick.gladow@gmail.com"
copyright:           "2019 Yannick Gladow"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yannick-cw/notion-ocr#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  notion-ocr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notion-ocr

tests:
  notion-ocr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notion-ocr
